### Syed Muhammad Zaid | 20B-052-SE

##### Task - 1

In [1]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_diabetes
from sklearn.model_selection import train_test_split
from sklearn.ensemble import BaggingRegressor, RandomForestRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.metrics import mean_squared_error

In [2]:
diabetes = load_diabetes()
X = diabetes.data
y = diabetes.target

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

def evaluate_model(model, X_train, X_test, y_train, y_test):
    model.fit(X_train, y_train)
    predictions = model.predict(X_test)
    mse = mean_squared_error(y_test, predictions)
    return mse

base_regressor = DecisionTreeRegressor()

bagging_regressor = BaggingRegressor(base_estimator=base_regressor, n_estimators=50, random_state=42)
bagging_mse = evaluate_model(bagging_regressor, X_train, X_test, y_train, y_test)

random_forest_regressor = RandomForestRegressor(n_estimators=50, random_state=42)
random_forest_mse = evaluate_model(random_forest_regressor, X_train, X_test, y_train, y_test)

print("Bagging Regressor MSE:", bagging_mse)
print("Random Forest Regressor MSE:", random_forest_mse)

/usr/local/lib/python3.10/dist-packages/sklearn/ensemble/_base.py:166: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(


Bagging Regressor MSE: 3056.494602247191
Random Forest Regressor MSE: 3044.1991280898874


##### Task - 2


In [3]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_diabetes
from sklearn.model_selection import train_test_split
from sklearn.ensemble import BaggingClassifier, RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, f1_score, confusion_matrix

In [9]:
def load_and_preprocess_data():
    diabetes = load_diabetes()
    X = diabetes.data
    y = diabetes.target
    threshold = 150
    y_class = (y > threshold).astype(int)
    return train_test_split(X, y_class, test_size=0.2, random_state=42)

def train_and_predict(model, X_train, X_test, y_train):
    model.fit(X_train, y_train)
    return model.predict(X_test)

def evaluate_model(y_test, predictions):
    accuracy = accuracy_score(y_test, predictions)
    f1 = f1_score(y_test, predictions)
    cm = confusion_matrix(y_test, predictions)
    return accuracy, f1, cm

def main():
    X_train, X_test, y_train, y_test = load_and_preprocess_data()

    base_classifier = DecisionTreeClassifier(random_state=42)
    bagging_classifier = BaggingClassifier(base_estimator=base_classifier, n_estimators=50, random_state=42)
    random_forest_classifier = RandomForestClassifier(n_estimators=50, random_state=42)

    bagging_pred = train_and_predict(bagging_classifier, X_train, X_test, y_train)
    bagging_accuracy, bagging_f1, bagging_cm = evaluate_model(y_test, bagging_pred)

    random_forest_pred = train_and_predict(random_forest_classifier, X_train, X_test, y_train)
    random_forest_accuracy, random_forest_f1, random_forest_cm = evaluate_model(y_test, random_forest_pred)

    print("Bagging Classifier Accuracy:", bagging_accuracy)
    print("Random Forest Classifier Accuracy:", random_forest_accuracy)

    print("Bagging Classifier F1 Score:", bagging_f1)
    print("Random Forest Classifier F1 Score:", random_forest_f1)

    print("Bagging Classifier Confusion Matrix:")
    print(bagging_cm)
    print("Random Forest Classifier Confusion Matrix:")
    print(random_forest_cm)

main()

/usr/local/lib/python3.10/dist-packages/sklearn/ensemble/_base.py:166: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(


Bagging Classifier Accuracy: 0.7415730337078652
Random Forest Classifier Accuracy: 0.7191011235955056
Bagging Classifier F1 Score: 0.7012987012987014
Random Forest Classifier F1 Score: 0.6666666666666666
Bagging Classifier Confusion Matrix:
[[39 10]
 [13 27]]
Random Forest Classifier Confusion Matrix:
[[39 10]
 [15 25]]


##### Task - 3

In [10]:
import numpy as np
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
from sklearn.ensemble import AdaBoostClassifier, RandomForestClassifier
from sklearn.metrics import accuracy_score, f1_score, confusion_matrix

def load_and_preprocess_data():
    data = load_breast_cancer()
    X = data.data
    y = data.target
    return train_test_split(X, y, test_size=0.2, random_state=42)

def train_and_predict(model, X_train, X_test, y_train):
    model.fit(X_train, y_train)
    return model.predict(X_test)

def evaluate_model(y_test, predictions):
    accuracy = accuracy_score(y_test, predictions)
    f1 = f1_score(y_test, predictions)
    cm = confusion_matrix(y_test, predictions)
    return accuracy, f1, cm

def main():
    X_train, X_test, y_train, y_test = load_and_preprocess_data()

    adaboost_classifier = AdaBoostClassifier(n_estimators=50, random_state=42)
    random_forest_classifier = RandomForestClassifier(n_estimators=50, random_state=42)

    adaboost_pred = train_and_predict(adaboost_classifier, X_train, X_test, y_train)
    adaboost_accuracy, adaboost_f1, adaboost_cm = evaluate_model(y_test, adaboost_pred)

    random_forest_pred = train_and_predict(random_forest_classifier, X_train, X_test, y_train)
    random_forest_accuracy, random_forest_f1, random_forest_cm = evaluate_model(y_test, random_forest_pred)

    print("AdaBoost Classifier Accuracy:", adaboost_accuracy)
    print("Random Forest Classifier Accuracy:", random_forest_accuracy)

    print("AdaBoost Classifier F1 Score:", adaboost_f1)
    print("Random Forest Classifier F1 Score:", random_forest_f1)

    print("AdaBoost Classifier Confusion Matrix:")
    print(adaboost_cm)
    print("Random Forest Classifier Confusion Matrix:")
    print(random_forest_cm)

main()


AdaBoost Classifier Accuracy: 0.9736842105263158
Random Forest Classifier Accuracy: 0.9649122807017544
AdaBoost Classifier F1 Score: 0.979020979020979
Random Forest Classifier F1 Score: 0.9722222222222222
AdaBoost Classifier Confusion Matrix:
[[41  2]
 [ 1 70]]
Random Forest Classifier Confusion Matrix:
[[40  3]
 [ 1 70]]


##### Task - 4

In [11]:
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
from sklearn.ensemble import AdaBoostClassifier, RandomForestClassifier
from sklearn.metrics import accuracy_score, f1_score, confusion_matrix

def load_and_preprocess_data():
    data = load_breast_cancer()
    X = data.data
    y = data.target
    return train_test_split(X, y, test_size=0.2, random_state=42)

def train_and_predict(model, X_train, X_test, y_train):
    model.fit(X_train, y_train)
    return model.predict(X_test)

def evaluate_model(y_test, predictions):
    accuracy = accuracy_score(y_test, predictions)
    f1 = f1_score(y_test, predictions)
    cm = confusion_matrix(y_test, predictions)
    return accuracy, f1, cm

def main():
    X_train, X_test, y_train, y_test = load_and_preprocess_data()

    adaboost_classifier = AdaBoostClassifier(n_estimators=50, random_state=42)
    random_forest_classifier = RandomForestClassifier(n_estimators=50, random_state=42)

    adaboost_pred = train_and_predict(adaboost_classifier, X_train, X_test, y_train)
    adaboost_accuracy, adaboost_f1, adaboost_cm = evaluate_model(y_test, adaboost_pred)

    random_forest_pred = train_and_predict(random_forest_classifier, X_train, X_test, y_train)
    random_forest_accuracy, random_forest_f1, random_forest_cm = evaluate_model(y_test, random_forest_pred)

    print("AdaBoost Classifier:")
    print("Accuracy:", adaboost_accuracy)
    print("F1 Score:", adaboost_f1)
    print("Confusion Matrix:")
    print(adaboost_cm)
    print()

    print("Random Forest Classifier:")
    print("Accuracy:", random_forest_accuracy)
    print("F1 Score:", random_forest_f1)
    print("Confusion Matrix:")
    print(random_forest_cm)

main()

AdaBoost Classifier:
Accuracy: 0.9736842105263158
F1 Score: 0.979020979020979
Confusion Matrix:
[[41  2]
 [ 1 70]]

Random Forest Classifier:
Accuracy: 0.9649122807017544
F1 Score: 0.9722222222222222
Confusion Matrix:
[[40  3]
 [ 1 70]]


##### Task - 5

In [12]:
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
from sklearn.ensemble import AdaBoostClassifier, RandomForestClassifier, StackingClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, f1_score, confusion_matrix

def load_and_preprocess_data():
    data = load_breast_cancer()
    X = data.data
    y = data.target
    return train_test_split(X, y, test_size=0.2, random_state=42)

def train_and_predict(model, X_train, X_test, y_train):
    model.fit(X_train, y_train)
    return model.predict(X_test)

def evaluate_model(y_test, predictions):
    accuracy = accuracy_score(y_test, predictions)
    f1 = f1_score(y_test, predictions)
    cm = confusion_matrix(y_test, predictions)
    return accuracy, f1, cm

def main():
    X_train, X_test, y_train, y_test = load_and_preprocess_data()

    base_estimators = [
        ('adaboost', AdaBoostClassifier(n_estimators=50, random_state=42)),
        ('random_forest', RandomForestClassifier(n_estimators=50, random_state=42))
    ]

    stacking_classifier = StackingClassifier(estimators=base_estimators, final_estimator=LogisticRegression())
    stacking_pred = train_and_predict(stacking_classifier, X_train, X_test, y_train)
    stacking_accuracy, stacking_f1, stacking_cm = evaluate_model(y_test, stacking_pred)

    print("Stacking Classifier:")
    print("Accuracy:", stacking_accuracy)
    print("F1 Score:", stacking_f1)
    print("Confusion Matrix:")
    print(stacking_cm)

main()

Stacking Classifier:
Accuracy: 0.9649122807017544
F1 Score: 0.9722222222222222
Confusion Matrix:
[[40  3]
 [ 1 70]]


##### Task - 6

In [13]:
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
from sklearn.ensemble import AdaBoostClassifier, RandomForestClassifier, StackingClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, f1_score, confusion_matrix

def load_and_preprocess_data():
    data = load_breast_cancer()
    X = data.data
    y = data.target
    return train_test_split(X, y, test_size=0.2, random_state=42)

def train_and_predict(model, X_train, X_test, y_train):
    model.fit(X_train, y_train)
    return model.predict(X_test)

def evaluate_model(y_test, predictions):
    accuracy = accuracy_score(y_test, predictions)
    f1 = f1_score(y_test, predictions)
    cm = confusion_matrix(y_test, predictions)
    return accuracy, f1, cm

def main():
    X_train, X_test, y_train, y_test = load_and_preprocess_data()

    base_estimators = [
        ('adaboost', AdaBoostClassifier(n_estimators=50, random_state=42)),
        ('random_forest', RandomForestClassifier(n_estimators=50, random_state=42))
    ]

    stacking_classifier = StackingClassifier(estimators=base_estimators, final_estimator=LogisticRegression())
    stacking_pred = train_and_predict(stacking_classifier, X_train, X_test, y_train)
    stacking_accuracy, stacking_f1, stacking_cm = evaluate_model(y_test, stacking_pred)

    print("Stacking Classifier:")
    print("Accuracy:", stacking_accuracy)
    print("F1 Score:", stacking_f1)
    print("Confusion Matrix:")
    print(stacking_cm)

    adaboost_classifier = AdaBoostClassifier(n_estimators=50, random_state=42)
    adaboost_pred = train_and_predict(adaboost_classifier, X_train, X_test, y_train)
    adaboost_accuracy, adaboost_f1, adaboost_cm = evaluate_model(y_test, adaboost_pred)

    print("\nAdaBoost Classifier:")
    print("Accuracy:", adaboost_accuracy)
    print("F1 Score:", adaboost_f1)
    print("Confusion Matrix:")
    print(adaboost_cm)

    random_forest_classifier = RandomForestClassifier(n_estimators=50, random_state=42)
    random_forest_pred = train_and_predict(random_forest_classifier, X_train, X_test, y_train)
    random_forest_accuracy, random_forest_f1, random_forest_cm = evaluate_model(y_test, random_forest_pred)

    print("\nRandom Forest Classifier:")
    print("Accuracy:", random_forest_accuracy)
    print("F1 Score:", random_forest_f1)
    print("Confusion Matrix:")
    print(random_forest_cm)

main()

Stacking Classifier:
Accuracy: 0.9649122807017544
F1 Score: 0.9722222222222222
Confusion Matrix:
[[40  3]
 [ 1 70]]

AdaBoost Classifier:
Accuracy: 0.9736842105263158
F1 Score: 0.979020979020979
Confusion Matrix:
[[41  2]
 [ 1 70]]

Random Forest Classifier:
Accuracy: 0.9649122807017544
F1 Score: 0.9722222222222222
Confusion Matrix:
[[40  3]
 [ 1 70]]
